### ISSUE TITLE
decide on strategy wrt text vs lexicon

### ISSUE THREAD

**Issue by amundo** [amundo/comparative-fulani#16]
currently have texts as input

but our component expects lexicons

what to do?

1. change the data into lexicons - write scripts to regenerate lexicon json files
    transcription => form
    translation => gloss
2. **change it on the fly - when you fetch the data, convert each sentence into a "word" 
    transcription => form
    translation => gloss
    not changing the data for the project, you're adapting it to the project**
3. change the component to expect texts - looks complicated
    this would be a different application

**Comment by morrisonhannah** [comment]
#2 is best because doesn't change the status of data, changes it in context of this project only
